### ISSUE TITLE
load_pretrained_model

### ISSUE THREAD

**Issue by disiji** [JonathanWenger/pycalib#2]
`pycalib/benchmark.py", line 1044, in load_pretrained_model
ModuleNotFoundError: No module named 'datasets'`

Thanks for publishing your code! When I was trying to reproduce your results on CIFAR, I change "classify_image" from False to True (I assumed this step is necessary, for generating data, but i might be wrong), then I got the error above, 
1. import path of "datasets" seems to need to be modified
2. there are no pretrained models under datasets/cifar100. Could you publish your pretrained models along with the datasets?
Thanks for your help!

**Comment by JonathanWenger** [comment]
You were right about `classify_images=True`. 

I should have made it clearer in the documentation on how to get the pretrainedmodels. From the class docstring of `CIFARData(Benchmark)`:

```python
    """
    Model evaluation using the benchmark vision dataset CIFAR-100.

    Implements a data generation method returning a new evaluation data set for each scoring round. Pre-trained CNNs are
    available at [1]_.
    ...
    .. [1] https://github.com/bearpaw/pytorch-classification
```
You can download the pretrained CNNs from https://github.com/bearpaw/pytorch-classification and save them to a folder, e.g. `datasets/cifar100/pretrained_networks`. I added the model definitions to `datasets/cifar100/models/`. I can't add the pretrained models to the github since they are too large. 

There was also an inclusion issue, where the code under `datasets/difar100/models/` was not added to the package. I fixed this now. After having downloaded the pretrained models, running the script `benchmark/CIFAR.py` should work now.
